inputs:
  python-version:
    description: "Python version to setup"
    required: false
    default: "3.9"

name: "Setup dependencies"
description: "Install all required dependencies for worflows to run."
runs:
  using: "composite"
  steps:
    - name: Install 3rd party dependencies
      run: sudo ./install-deps.sh
      shell: bash

    - name: Setup sccache # for speeding up Rust builds
      uses: mozilla-actions/sccache-action@v0.0.7
      with:
        disable_annotations: true # it is very spammy, but useful for diagnostics

    - name: Enable sccache
      run: |
        echo SCCACHE_GHA_ENABLED=true >> $GITHUB_ENV
        echo RUSTC_WRAPPER=sccache >> $GITHUB_ENV
      shell: bash

    - name: Install uv & Python
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"
        python-version: ${{ inputs.python-version }}

    - name: Install the project
      run: uv sync
      shell: bash
