[jefferson]
fetch.pypi = "jefferson"
src.pypi = "jefferson"

[ubi_reader]
fetch.pypi = "ubi_reader"
src.pypi = "ubi_reader"

[treelib]
fetch.pypi = "treelib"
src.pypi = "treelib"

[pyfatfs]
fetch.pypi = "pyfatfs"
src.pypi = "pyfatfs"

[e2fsprogs]
fetch.github = "onekey-sec/e2fsprogs"
src.github_tag = "onekey-sec/e2fsprogs"
